---
title: "Test overall measure estimation functions: computation-overall-measure.R "
author: "Jiajie Chen, Xiao Su"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

source_files <- function(files){
  for(i in 1:length(files)){
    source(files[i])
  }
}

rhoBoundarySarmanov <- function(a1, b1, a2, b2){
  cc <- sqrt(a1*a2*b1*b2)/sqrt((a1+b1+1)*(a2+b2+1))
  upper_bound <- cc/max(a1*b2, a2*b1)
  lower_bound <- -cc/max(a1*a2, b1*b2)
  rho_range<-c(lower_bound,upper_bound)
  names(rho_range)<-c("lower_bound","upper_bound")
  return(rho_range)
}

parmsToTransformed <- function(parms_original) {
  a1 <- parms_original[1]
  b1 <- parms_original[2]
  a2 <- parms_original[3]
  b2 <- parms_original[4]
  loga1 <- log(a1); 
  logb1 <- log(b1)
  loga2 <- log(a2); 
  logb2 <- log(b2)
  if(length(parms_original) >= 5){
    rho <- parms_original[5]
    cc <- sqrt(a1*a2*b1*b2)/sqrt((a1+b1+1)*(a2+b2+1))
    upper_bound <- cc/max(a1*b2, a2*b1)
    lower_bound <- -cc/max(a1*a2, b1*b2)
    eta <- logit((rho - lower_bound) / (upper_bound-lower_bound))
  } else{
    rho <- 0  
  }
  
  parms_transformed <- c(loga1,logb1,loga2,logb2,eta)
  names(parms_transformed) <- c('loga1','logb1','loga2','logb2','eta')
  return(parms_transformed)
}

expit <- function(x) exp(x)/(1+exp(x))


```

## Create test cases


```{r}
sar_mat_template <- matrix( c(-3.607379e+01 , 3.001928e+01 , 3.491566e+00, -3.553578e+00 , 1.250555e-05,
                               3.001928e+01 ,-3.309083e+01, -3.507144e+00,  3.576321e+00, -1.455192e-05,
                                3.491566e+00, -3.507144e+00, -4.152234e+01,  3.671382e+01 , 7.503331e-06,
                               -3.553578e+00 , 3.576321e+00 , 3.671382e+01, -4.082029e+01 ,-1.023182e-05,
                              1.250555e-05, -1.455192e-05 , 7.503331e-06, -1.023182e-05, -4.752110e-05
                            ),nrow=5,ncol=5,byrow=TRUE)
indep_mat_template <- matrix( c(-3.607379e+01 , 3.001928e+01 , 3.491566e+00, -3.553578e+00 , 
                               3.001928e+01 ,-3.309083e+01, -3.507144e+00,  3.576321e+00,
                                3.491566e+00, -3.507144e+00, -4.152234e+01,  3.671382e+01 , 
                               -3.553578e+00 , 3.576321e+00 , 3.671382e+01, -4.082029e+01 
                            ),nrow=4,ncol=4,byrow=TRUE)

```


```{r}
num_cases <- 10000
set.seed(1000)
a1 <- runif( num_cases , min = 0.001 , max = 200)
b1 <- runif( num_cases , min = 0.001 , max = 200)
a2 <- runif( num_cases , min = 0.001 , max = 200)
b2 <- runif( num_cases , min = 0.001 , max = 200)
model <- sample(c('Sarmanov','Independent'), size=num_cases, replace=TRUE)
measure <- sample(c('OR','RR','RD'), size=num_cases, replace=TRUE)
test_cases <- data.frame(a1,b1,a2,b2, model, measure)
## sample rho and hessian_log
hessian_log_list <- list()
rho <- rep(0, num_cases)
for(i in 1:num_cases){
  rho_range <- rhoBoundarySarmanov(test_cases[i,'a1'], test_cases[i,'b1'], test_cases[i,'a2'],
                      test_cases[i,'b2']) 
  rho[i] <- runif( 1 , min = rho_range[1] , max = rho_range[2])
  if(model[i] == 'Sarmanov'){
    hessian_log_list[[i]] <- sar_mat_template * log(test_cases[i,'a1'])/log(3.1084070) * runif( 1 , min = 0.001 , max = 3)
  } else{
    hessian_log_list[[i]] <- indep_mat_template * log(test_cases[i,'a1'])/log(3.1084070) * runif( 1 , min = 0.001 , max = 3)
  }
    

}
test_cases['rho'] <- rho 
alpha <- 0.05
save(source_files , hessian_log_list, test_cases, alpha ,file = 'test_cases.rda')
```



```{r}

```

## Old version


```{r}
options(warn=-1)
rm(list = ls())
load(file = 'test_cases.rda')
old_verrsion_path <- c('G:/My Drive/ShareFolder/mmeta_package/working/mmeta/R/overall.R',
                       'G:/My Drive/ShareFolder/mmeta_package/working/mmeta/R/MLE.R')
source_files(old_verrsion_path)

test_cases['point_old'] <- rep(NA, nrow(test_cases))
test_cases['lower_old'] <- rep(NA, nrow(test_cases))
test_cases['upper_old'] <- rep(NA, nrow(test_cases))

for(i in 1:nrow(test_cases)){
          MLE <- c(a1 = test_cases[i,'a1'], b1=test_cases[i,'b1'],a2= test_cases[i,'a2'],
                              b2=test_cases[i,'b2'],rho=test_cases[i,'rho'])
          estimate <- overall(MLE, hessian_log_list[[i]], test_cases[i,'measure'], test_cases[i,'model'], alpha=alpha)
          test_cases['point_old'] <- estimate$overall
          test_cases['lower_old'] <- estimate$CI[1]
          test_cases['upper_old'] <- estimate$CI[2]

  
}

save(source_files , hessian_log_list, test_cases, alpha ,file = 'test_cases.rda')


```




## New version

```{r}
options(warn=-1)
rm(list = ls())
load(file = 'test_cases.rda')

new_verrsion_path <- c('G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/computation-overall-measure.R',
                       'G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/config-global-constant.R',
                       'G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/utility-others.R'
                       )
source_files(new_verrsion_path)

test_cases['point_new'] <- rep(NA, nrow(test_cases))
test_cases['lower_new'] <- rep(NA, nrow(test_cases))
test_cases['upper_new'] <- rep(NA, nrow(test_cases))



for(i in 1:nrow(test_cases)){
  parms_original <- c(a1 = test_cases[i,'a1'], b1=test_cases[i,'b1'],a2= test_cases[i,'a2'],
                              b2=test_cases[i,'b2'])
          
  estimate <- overallMeasure(parms_original, 
                 hessian_log_list[[i]] , measure = test_cases[i,'measure'], alpha = alpha )
  
  test_cases['point_new'] <- estimate$overall
  test_cases['lower_new'] <- estimate$CI[1]
  test_cases['upper_new'] <- estimate$CI[2]
          
}



```


## Comparison

```{r}

test_cases['diff_point'] <- abs(test_cases['point_new'] - test_cases['point_old'])
test_cases['diff_lower'] <- abs(test_cases['lower_new'] - test_cases['lower_old'])
test_cases['diff_upper'] <- abs(test_cases['upper_new'] - test_cases['upper_old'])


```

point estimates
```{r}
summary(test_cases['diff_point'] )

```
lower CI
```{r}
summary(test_cases['diff_lower'] )

```

upper CI

```{r}
summary(test_cases['diff_upper'] )

```



