---
title: "Test SingleTable essential: one off "
author: "Jiajie Chen, Xiao Su"
date: "`r Sys.Date()`"
output: html_document
---

## Enviroment setup


```{r}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
source_all_files <- function(path){
  files <- list.files(path)
  for(i in 1:length(files)){
    full_path <- paste(path, files[i],sep="")
    source(full_path)
  }
}
### Load the new version
library(ggplot2)
new_verrsion_path <- 'G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/'
source_all_files(new_verrsion_path)


```

## Test sampling  method

### Create object

```{r}
single_table_obj_samling <- SingleTable.create(a1=0.5, b1=0.5, a2=0.5, b2=0.5,
                              rho=0.5, y1=40, n1=96, y2=49, n2=109,
                              model="Sarmanov",measure="OR")
```

### model fit

```{r}
single_table_obj_samling <- SingleTable.modelFit(single_table_obj_samling, method = 'sampling')
str(single_table_obj_samling)
```
### Summary

```{r}
single_table_obj_samling <- SingleTable.summary(single_table_obj_samling, alpha = 0.05)
str(single_table_obj_samling)
```
## overlay density: 

ggplot2: raw
```{r}
SingleTable.plot(single_table_obj_samling, type = 'overlay',use_ggplot2 = TRUE, xlim = c(0,4), add_vertical = 1)
```
ggplot2: add additional attributes

```{r}
plot_obj <- SingleTable.plot(single_table_obj_samling, type = 'overlay',use_ggplot2 = TRUE, xlim = c(0,4), add_vertical = 1)
plot_obj + theme(panel.background = element_blank()) + xlab('Relative Risk')
```

### Plot side-by-side

ggplot2: raw
```{r}
SingleTable.plot(single_table_obj_samling, type = 'side_by_side',use_ggplot2 = TRUE, 
                 xlim = c(0,4), add_vertical = 1)

```

ggplot2: add additonal attributes
```{r}
plot_obj <- SingleTable.plot(single_table_obj_samling, type = 'side_by_side',use_ggplot2 = TRUE, 
                 xlim = c(0,4), add_vertical = 1)

plot_obj + theme(panel.background = element_blank()) + xlab('Relative Risk')
```



## Test sampling  method

### Create object

```{r}
single_table_obj_exact <- SingleTable.create(a1=0.5, b1=0.5, a2=0.5, b2=0.5,
                              rho=0.5, y1=40, n1=96, y2=49, n2=109,
                              model="Sarmanov",measure="OR")

```

### Model fit
```{r}
single_table_obj_exact <- SingleTable.modelFit(single_table_obj_exact, method = 'exact')
str(single_table_obj_exact)

```
### Summary

```{r}
single_table_obj_exact <- SingleTable.summary(single_table_obj_exact, alpha = 0.05)
str(single_table_obj_exact)

```


### Plot: overlay

```{r}
SingleTable.plot(single_table_obj_exact, type = 'overlay',use_ggplot2 = TRUE, xlim = c(0,4), add_vertical = 1)
```

ggplot2: add additional attributes

```{r}
plot_obj <- SingleTable.plot(single_table_obj_exact, type = 'overlay',use_ggplot2 = TRUE, xlim = c(0,4), add_vertical = 1)
plot_obj + theme(panel.background = element_blank()) + xlab('Relative Risk')
```


### Plot: side-by-side

ggplot2: raw
```{r}
SingleTable.plot(single_table_obj_exact, type = 'side_by_side',use_ggplot2 = TRUE, 
                 xlim = c(0,4), add_vertical = 1)

```


ggplot2: add additonal attributes
```{r}
plot_obj <- SingleTable.plot(single_table_obj_exact, type = 'side_by_side',use_ggplot2 = TRUE, 
                 xlim = c(0,4), add_vertical = 1)

plot_obj + theme(panel.background = element_blank()) + xlab('Relative Risk')
```