---
title: "Test loglikelihood functions: computation-loglikelihood.R "
author: "Jiajie Chen, Xiao Su"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

source_files <- function(files){
  for(i in 1:length(files)){
    source(files[i])
  }
}

rhoBoundarySarmanov <- function(a1, b1, a2, b2){
  cc <- sqrt(a1*a2*b1*b2)/sqrt((a1+b1+1)*(a2+b2+1))
  upper_bound <- cc/max(a1*b2, a2*b1)
  lower_bound <- -cc/max(a1*a2, b1*b2)
  rho_range<-c(lower_bound,upper_bound)
  names(rho_range)<-c("lower_bound","upper_bound")
  return(rho_range)
}

parmsToTransformed <- function(parms_original) {
  a1 <- parms_original[1]
  b1 <- parms_original[2]
  a2 <- parms_original[3]
  b2 <- parms_original[4]
  loga1 <- log(a1); 
  logb1 <- log(b1)
  loga2 <- log(a2); 
  logb2 <- log(b2)
  if(length(parms_original) >= 5){
    rho <- parms_original[5]
    cc <- sqrt(a1*a2*b1*b2)/sqrt((a1+b1+1)*(a2+b2+1))
    upper_bound <- cc/max(a1*b2, a2*b1)
    lower_bound <- -cc/max(a1*a2, b1*b2)
    eta <- logit((rho - lower_bound) / (upper_bound-lower_bound))
  } else{
    rho <- 0  
  }
  
  parms_transformed <- c(loga1,logb1,loga2,logb2,eta)
  names(parms_transformed) <- c('loga1','logb1','loga2','logb2','eta')
  return(parms_transformed)
}

expit <- function(x) exp(x)/(1+exp(x))


```

## Create test cases


```{r}
num_cases <- 10000
set.seed(1000)
a1 <- runif( num_cases , min = 0.001 , max = 200)
b1 <- runif( num_cases , min = 0.001 , max = 200)
a2 <- runif( num_cases , min = 0.001 , max = 200)
b2 <- runif( num_cases , min = 0.001 , max = 200)
theta <- runif( num_cases , min = 0.001 , max = 50)
n1 <- sample(1:5000,num_cases,replace=T)
n2 <- sample(1:5000,num_cases,replace=T)
model <- sample(c('Sarmanov','Independent'), size=num_cases, replace=TRUE)
measure <- sample(c('OR','RR','RD'), size=num_cases, replace=TRUE)
test_cases <- data.frame(theta,a1,b1,a2,b2, n1, n2, model, measure)
## sample rho and y1, y2
rho <- rep(0, num_cases)
y1 <- rep(0, num_cases)
y2 <- rep(0, num_cases)
for(i in 1:num_cases){
  rho_range <- rhoBoundarySarmanov(test_cases[i,'a1'], test_cases[i,'b1'], test_cases[i,'a2'],
                      test_cases[i,'b2']) 
  rho[i] <- runif( 1 , min = rho_range[1] , max = rho_range[2])
  y1[i] <- sample(0:test_cases[i,'n1'],1,replace=T)
  y2[i] <- sample(0:test_cases[i,'n2'],1,replace=T)
}
test_cases['rho'] <- rho 
test_cases['y1'] <- y1 
test_cases['y2'] <- y2

save(source_files, rhoBoundarySarmanov, parmsToTransformed,test_cases,file = 'test_cases.rda')
```

## Old version


```{r}
options(warn=-1)
rm(list = ls())
load(file = 'test_cases.rda')
old_verrsion_path <- c('G:/My Drive/ShareFolder/mmeta_package/working/mmeta/R/MLE.R')
source_files(old_verrsion_path)

test_cases['loglik_old'] <- rep(NA, nrow(test_cases))
for(i in 1:nrow(test_cases)){
          parms_original <- c(a1 = test_cases[i,'a1'], b1=test_cases[i,'b1'],a2= test_cases[i,'a2'],
                              b2=test_cases[i,'b2'],rho=test_cases[i,'rho'])
          mypar <- parmsToTransformed(parms_original)
          mydat <- list(y1=test_cases[i,'y1'],y2=test_cases[i,'y2'],n1=test_cases[i,'n1'])

          if(test_cases[i,'model'] == 'Sarmanov'){
              test_cases['loglik_old'] <- myLik.sar.log(mypar, mydat)          
          } else{
            
             test_cases['loglik_old'] <- myLik.indep.log(mypar, mydat)
          }
  
  
}

save(source_files,parmsToTransformed, test_cases,file = 'test_cases.rda')


```




## New version

```{r}
options(warn=-1)
rm(list = ls())
load(file = 'test_cases.rda')

new_verrsion_path <- c('G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/computation-loglikelihood.R',
                       'G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/utility-others.R',
                       'G:/My Drive/ShareFolder/mmeta_package/working/new_mmeta_dev/func_dev/config-global-constant.R'
                       )
source_files(new_verrsion_path)



test_cases['loglik_new'] <- rep(NA, nrow(test_cases))
for(i in 1:nrow(test_cases)){
         parms_original <- c(a1 = test_cases[i,'a1'], b1=test_cases[i,'b1'],a2= test_cases[i,'a2'],
                              b2=test_cases[i,'b2'],rho=test_cases[i,'rho'])
          mypar <- parmsToTransformed(parms_original)
          mydat <- list(y1=test_cases[i,'y1'],y2=test_cases[i,'y2'],n1=test_cases[i,'n1'])

          if(test_cases[i,'model'] == 'Sarmanov'){
              test_cases['loglik_new'] <- logLikSar(mypar, mydat)          
          } else{
            
             test_cases['loglik_new'] <- logLikIndep(mypar, mydat)
          }
  
}



```


## Comparison

```{r}

test_cases['diff'] <- test_cases['loglik_new'] - test_cases['loglik_old']
head(test_cases)

```


```{r}
summary(test_cases['diff'] )

```
